name: 🚀 Feature Request
description: Suggest an idea or enhancement for omniadapters
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for helping improve omniadapters!

        Before submitting a feature request:
        - 🔍 **Search existing issues and discussions** to avoid duplicates
        - 💬 **Consider starting a discussion** first for broader feedback: [Discussions](https://github.com/omniadapters/omniadapters/discussions)
        - 📖 **Check our roadmap** if available in the documentation

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What kind of feature are you proposing?
      options:
        - "🎯 New Feature - Completely new functionality"
        - "✨ Enhancement - Improvement to existing feature"
        - "🔧 API Change - Modification to public API"
        - "⚡ Performance - Speed or efficiency improvement"
        - "🎨 Developer Experience - Better DX/ergonomics"
        - "🏗️ Architecture - Structural improvements"
        - "📦 Integration - Third-party service/tool support"
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: |
        Clear description of the problem you're facing:
        - What are you trying to accomplish?
        - What limitations are you encountering?
        - How does this affect your workflow?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to this problem
      placeholder: |
        Describe how you envision this feature working:
        - What would the API/interface look like?
        - How would users interact with it?
        - Include code examples if applicable
      render: python
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: |
        - Alternative approaches you've tried
        - Workarounds you're currently using
        - Why these alternatives are not sufficient

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Provide a concrete example of how you'd use this feature
      placeholder: |
        ```python
        # Example code showing how you'd use this feature
        from omniadapters import NewFeature

        # Your use case here
        result = NewFeature.do_something()
        ```
      render: python
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Expected Impact
      description: How many users would benefit from this feature?
      options:
        - "🌍 High - Benefits most users"
        - "👥 Medium - Benefits specific user groups"
        - "👤 Low - Niche use case"
        - "❓ Unknown"
    validations:
      required: true

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes?
      options:
        - "✅ No - Backward compatible"
        - "⚠️ Yes - Would break existing code"
        - "❓ Unsure - Needs investigation"
    validations:
      required: true

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Considerations
      description: Any thoughts on how this might be implemented?
      placeholder: |
        - Technical constraints to consider
        - Dependencies or prerequisites
        - Performance implications
        - Security considerations

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Are you interested in contributing to this feature?
      options:
        - label: I am willing to submit a PR to implement this feature
          required: false
        - label: I can help with testing and feedback
          required: false
        - label: I can contribute documentation for this feature
          required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: |
        - Links to similar features in other libraries
        - Research papers or articles
        - Screenshots or mockups
        - Related issues or PRs

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature aligns with omniadapters' goals
          required: true
        - label: I have provided a clear use case
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        **Thank you for your feature request! 🎉**

        Your input helps shape the future of omniadapters. A maintainer will review your proposal soon.